@echo off
echo Starting Backend...
start /min cmd /k "cd Backend && npm run dev"

echo Starting Frontend...
start /min cmd /k "cd Frontend && npm run dev"

echo Waiting for Frontend to start...
timeout /t 5 >nul

echo Opening Browser...
start http://localhost:5173/
